export const SUPPORTED_REDUX_FUNCTIONS = {
  TOGGLE_MODAL: "TOGGLE_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",

  SET_SCREEN_WIDTH: "SET_SCREEN_WIDTH",

  // LoginManager
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};
