import type { NextPage } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";
import { isAuth } from "../utils/utiltyHelper";

const Home: NextPage = () => {
  const auth = useSelector((state: any) => {
    return state.LoginManager.auth;
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{isAuth(auth) ? "welcome back" : "hello world"}</main>
    </>
  );
};

export default Home;
